---
shared:
  mailer: &shared_mailer
    send_application: &shared_send_application_mailer
      subject: "Nous avons bien reçu votre demande d’accès"
    validate_application: &shared_validate_application_mailer
      subject: "Votre demande a été validée"
    review_application: &shared_review_application_mailer
      subject: "Votre demande requiert des modifications"
    refuse_application: &shared_refuse_application_mailer
      subject: "Votre demande a été refusée"
    notify_application_sent: &shared_notify_appication_sent_mailer
      subject: "Nouvelle demande sur DataPass"
    create_application: &shared_create_application_mailer
      subject: "Votre demande a été enregistrée"
    notify: &shared_notify_mailer
      subject: "Vous avez un nouveau message concernant votre demande"

franceconnect:
  label: FranceConnect
  support_email: support.partenaires@franceconnect.gouv.fr
  mailer: *shared_mailer

api_particulier:
  label: API Particulier
  support_email: contact@particulier.api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_sandbox:
  label: API Impôt particulier (Bac à sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_production:
  label: API Impôt particulier (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_fc_sandbox:
  label: API Impôt particulier (Bac à sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_impot_particulier_fc_production:
  label: API Impôt particulier (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_r2p_sandbox:
  label: API R2P (Bac à sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_r2p_production:
  label: API R2P (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ficoba_sandbox:
  label: API FICOBA (Bac à sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_ficoba_production:
  label: API FICOBA (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_droits_cnam:
  label: API Droits CNAM
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_entreprise:
  label: API Entreprise
  support_email: support@entreprise.api.gouv.fr
  mailer:
    <<: *shared_mailer
    review_application:
      subject: "✒️ Votre demande requiert des modifications"

preuve_covoiturage:
  label: Registre de preuve de covoiturage
  support_email: contact@covoiturage.beta.gouv.fr
  mailer: *shared_mailer

le_taxi_clients:
  label: le.Taxi
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

le_taxi_chauffeurs:
  label: le.Taxi
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

cartobio:
  label: CartoBio
  support_email: cartobio@beta.gouv.fr
  mailer: *shared_mailer

aidants_connect:
  label: Aidants Connect
  support_email: contact@aidantsconnect.beta.gouv.fr
  mailer: *shared_mailer

francerelance_fc:
  label: FranceRelance - Guichet FranceConnect
  support_email: support.partenaires@franceconnect.gouv.fr
  mailer: *shared_mailer

api_service_national:
  label: API Service National
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_statut_etudiant:
  label: API Statut étudiant
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_hermes_sandbox:
  label: API Hermes (Bac à sable)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

api_hermes_production:
  label: API Hermes (Production)
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer

hubee:
  label: Hubee
  support_email: contact@api.gouv.fr
  mailer: *shared_mailer
